# See: https://github.com/goss-org/goss/blob/master/docs/manual.md#goss-manual

package:
  curl: { installed: true }
  ffmpeg: { installed: true }
  gifsicle: { installed: true }
  gosu: { installed: true }
  jpegoptim: { installed: true }
  locales-all: { installed: true }
  locales: { installed: true }
  mariadb-client: { installed: true }
  nano: { installed: true }
  optipng: { installed: true }
  pngquant: { installed: true }
  postgresql-client: { installed: true }
  unzip: { installed: true }
  wget: { installed: true }
  zip: { installed: true }

user:
  www-data:
    exists: true
    uid: 33
    gid: 33
    groups:
      - www-data
    home: /var/www
    shell: /usr/sbin/nologin

command:
  php-version:
    exec: php -v
    exit-status: 0
    stdout:
      - PHP {{ .Env.EXPECTED_PHP_VERSION }}
    stderr: []

  php-extensions:
    exec: php -m
    exit-status: 0
    stdout:
      - bcmath
      - Core
      - ctype
      - curl
      - date
      - dom
      - exif
      - fileinfo
      - filter
      - gd
      - hash
      - iconv
      - imagick
      - intl
      - json
      - libxml
      - mbstring
      - mysqlnd
      - openssl
      - pcntl
      - pcre
      - PDO
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - Phar
      - posix
      - readline
      - redis
      - Reflection
      - session
      - SimpleXML
      - sodium
      - SPL
      - sqlite3
      - standard
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - zip
      - zlib
    stderr: []

  php-info:
    exec: php -i
    exit-status: 0
    stdout:
      # Make sure we don't run any debug builds
      - Debug Build => no
      # Make sure signal handling is enabled
      - Zend Signal Handling => enabled
      # Ensure mbstring is around and used
      - Zend Multibyte Support => provided by mbstring
      # For the modern hipsters out there
      - IPv6 Support => enabled
      # Security: not expose PHP information to users
      - expose_php => Off => Off
      # Ensure memory limit is configured correctly
      - memory_limit => 128M => 128M
      # Ensure post_max_size is configured correctly
      - post_max_size => 61M => 61M
      # EXIF is enabled
      - EXIF Support => enabled
      # GD is enabled and configured correctly
      - GD Support => enabled
      - FreeType Support => enabled
      - FreeType Linkage => with freetype
      - GIF Read Support => enabled
      - GIF Create Support => enabled
      - JPEG Support => enabled
      - PNG Support => enabled
      - WBMP Support => enabled
      - XPM Support => enabled
      - XBM Support => enabled
      - WebP Support => enabled
      - BMP Support => enabled
      - AVIF Support => enabled
      - TGA Read Support => enabled
      # imagick is enabled and configured correctly
      - "imagick module => enabled"
      # PDO is enabled with the right drivers
      - PDO support => enabled
      - PDO drivers => mysql, pgsql, sqlite
      # Redis is enabled
      - Redis Support => enabled
      # session is enabled and configured correctly
      - Session Support => enabled
      - Registered save handlers => files user redis rediscluster

  forego-version:
    exit-status: 0
    exec: 'forego version'
    stdout:
      - dev
    stderr: []

  gomplate-version:
    exit-status: 0
    exec: 'gomplate -v'
    stdout:
      - gomplate version
    stderr: []

  gosu-version:
    exit-status: 0
    exec: 'gosu --version'
    stdout:
      - '1.14'
    stderr: []

{{ if eq .Env.PHP_BASE_TYPE "nginx" }}
  nginx-version:
    exit-status: 0
    exec: 'nginx -v'
    stdout: []
    stderr:
      - 'nginx version: nginx'
{{ end }}

{{ if eq .Env.PHP_BASE_TYPE "apache" }}
  apache-version:
    exit-status: 0
    exec: 'apachectl -v'
    stdout:
      - 'Server version: Apache/'
    stderr: []
{{ end }}
