#!/usr/bin/env bash

declare -r service="${PF_SERVICE:=worker}"
declare -r user="${PF_USER:=www-data}"

# default [docker run] flags
declare -ra flags=(
    --user "${user}"
    --env TERM
    --env COLORTERM
    --workdir /var/www
)

exec docker compose exec \
    "${flags[@]}" \
    "${service}" \
    php artisan "${@}"
