#!/usr/bin/env bash

set -e -o errexit -o nounset -o pipefail

# [dottie] command flags
declare -a dottie_flags=()

# [dottie update]
if [[ "${1:-}" == "update" ]]; then
    echo ''
    # dottie_flags+=(--no-validate)
    # dottie_flags+=(--backup-file /var/www/storage/docker/dot-env-file-backup)
fi

# [dottie set]
if [[ "${1:-}" == "set" ]]; then
    dottie_flags+=(--no-validate)
fi

# run dottie within a container
exec scripts/shell dottie "$@" "${dottie_flags[@]}"
