#!/usr/bin/env bash

set -e -o errexit -o nounset -o pipefail

# [dottie] flags
declare -a dottie_flags=()

# [dottie] skip validation when running in the container
if [[ "${1:-}" == "update" ]]; then
    dottie_flags+=(--no-validate)
fi

# run dottie within a container
exec scripts/shell dottie "$@" "${dottie_flags[@]}"
