#!/usr/bin/env bash

set -e -o errexit -o nounset -o pipefail

declare project_root="${PWD}"

command -v git &>/dev/null && project_root=$(git rev-parse --show-toplevel)

# renovate: datasource=docker depName=ghcr.io/jippi/dottie
declare dottie_version="v0.14.2"
declare user="${PF_USER:=www-data}"

# default [docker run] flags
declare -a flags=(
    --rm
    --user "${user}"
    --env TERM
    --env COLORTERM
    --volume "${project_root}:/var/www"
    --workdir /var/www
)

# if the shell is interactive, attach the tty and stdin to the container
tty -s && [ $# -eq 0 ] && flags+=(--interactive --tty)

# run dottie
exec docker run "${flags[@]}" "ghcr.io/jippi/dottie:${DOTTIE_VERSION:-${dottie_version}}" "$@"
