#!/usr/bin/env bash

set -e -o errexit -o nounset -o pipefail

declare project_root="${PWD}"
command -v git &>/dev/null && project_root=$(git rev-parse --show-toplevel)

# shellcheck source=lib/shared.sh
source "${project_root}/scripts/lib/shared.sh"

# @renovate datasource=docker depName=mariadb versioning=semver-coerced
DB_VERSION="11.4"

# @renovate datasource=docker depName=php versioning=semver-coerced
DOCKER_APP_PHP_VERSION="8.3"

# @renovate datasource=github-releases depName=jippi/docker-pixelfed versioning=semver-coerced
DOCKER_APP_RELEASE="v0.14"

# @renovate datasource=docker depName=nginxproxy/nginx-proxy versioning=semver-coerced
DOCKER_PROXY_VERSION="1.4"

# @renovate datasource=docker depName=redis versioning=semver-coerced
DOCKER_REDIS_VERSION="7.2"

__dottie set DB_VERSION="${DB_VERSION}"
__dottie set DOCKER_APP_PHP_VERSION="${DOCKER_APP_PHP_VERSION}"
__dottie set DOCKER_APP_RELEASE="${DOCKER_APP_RELEASE}"
__dottie set DOCKER_PROXY_VERSION="${DOCKER_PROXY_VERSION}"
__dottie set DOCKER_REDIS_VERSION="${DOCKER_REDIS_VERSION}"
